version: '3.5'

x-env:
  &env
  CI_DOCKER_NETWORK: "gomigrator_dev_default"

x-test-svc:
  &test-svc
  image: golang:1.17
  working_dir: /go/src/app-dev
  volumes:
    - ./:/go/src/app-dev
    # Saves us redownloading every time, as this is not a long running service
    - ./.module_cache:/go/pkg/mod
    # We mount this so we can dockertest for integration testing
    - /var/run/docker.sock:/var/run/docker.sock

services:
  unit:
    <<: *test-svc
    environment:
      <<: *env

  integration:
    <<: *test-svc
    environment:
      <<: *env
      # This enables integration tests
      CI_INTEGRATION_TESTS_ENABLED: "true"
