version: '3.5'

x-test-svc:
  &test-svc
  build: 
    context: ./
  working_dir: /go/src/app-dev
  volumes:
    - ../:/go/src/app-dev
    # Saves us redownloading every time, as this is not a long running service
    - ./.module_cache:/go/pkg/mod

services:
  unit:
    <<: *test-svc

  postgres-integration:
    <<: *test-svc
    environment:
      # This enables integration tests
      CI_INTEGRATION_TESTS_ENABLED: "true"
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_DATABASE: ${POSTGRES_DB}
      DB_PORT: 5432

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
