name: "Run tests"

on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**/*.md'
      - '*.md'
      - 'Makefile'
      - 'LICENSE'
      - 'docker-compose.yaml'

jobs:
  unit_test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.15.x
          - 1.16.x
          - 1.17.x
    permissions:
      repository-projects: read
    # Cancel current run if new changes are pushed
    concurrency: 
      group: unit-test-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Unit Test"
        run: go test -cover ./...


